Js 引擎是基于单线程事件循环概念构建的，同一时刻只能执行一个代码块，每当一段代码准备执行时，都会被添加到任务队列。

## Promise 生命周期

* 进行中 (pending)，此时是未处理 (unsettled)

* 异步操作完成后，会变为已处理 (settled)，Promise 可能会进入到以下两个状态中的一个：

  `Fullfilled 和 Rejected`

当 Promise 状态发生改变时，可通过 `then()` 方法采取一些相应的操作。`then()` 方法接收两个参数：第一个是 Promise 状态变为 fullfilled 时要调用的函数，第二个状态变为 rejected 要调用的函数。

```js
let promise = readFile("example.txt");

promise.then(function(contents) {
    // 完成处理程序
}, function(err) {
    // 拒绝处理程序
});

// catch()方法是专门接收拒绝处理程序的
promise.catch(function(err) {
    // ...
});
```

如果一个 Promise 处于已处理状态，在这之后添加到任务队列中的处理程序任将执行。这意味着在完成处理程序内部再添加一个 `Promise.then()` 的处理程序也是完全可行的。注意，每次调用 then() 或 catch() 都会创建一个新任务。



### 创建未完成的 Promise

Promise 可用构造函数创建，该构造函数只接收一个参数：执行器函数。该函数接收两个参数：`resolve() 和 reject()`。当执行器成功执行时调用 resolve()，否则调用 reject()

```js
let fs = require("fs");

function readFile(fileName) {
    return new Promise(function(resolve, reject) {
        fs.readFile(fileName, {encoding: "utf8"}, 
                    function(err, contents) {
            if (err) {
                // 这个参数会传入相应的拒绝处理程序中
                reject(err);
                return;
            }
			// 这个参数会传入相应的完成处理程序中
            resolve(contents);
        });
    });
}

let promise = readFile("example.txt");

promise.then(function(contents) {
    // 完成处理程序
}, function(err) {
    // 拒绝处理程序
});

// catch()方法是专门接收拒绝处理程序的
promise.catch(function(err) {
    // ...
});
```

注意，Promise 的执行器总是会立即执行，完成处理程序和拒绝处理程序总是会在执行器完成后被添加到任务队列的末尾。

```js

let promise = new Promise(function(resolve, reject) {
    console.log("Promise");
    resolve();
});

promise.then(function() {
    console.log("resolved");
});

console.log("Hi");

/*
output:
    Promise
    Hi
    resolved
*/
```



### 创建已处理的 Promise

这种方式需向 Promise 的静态方法传递一个参数，这个参数会被传递到 then() 方法的处理程序中。这些方法返回一个完成态的 Promise

```js
let promise1 = Promise.resolve(42);
let promise2 = Promise.reject(43);

promise1.then(function(value) {
    console.log(value); // 42
});

promise2.catch(function(value) {
    console.log(value); // 43
});
```



### 非 Promise 的 Thenable 对象

拥有 then() 方法并且接收 resolve 和 reject 这两个参数的普通对象就是非 Promise 的 Thenable 对象。

如果向创建已处理 Promise 的方法传入一个非 Promise 的 Thenable 对象，则这些方法会创建一个新的 Promise，并在 then() 函数中被调用

```js
let thenable = {
    then: function(resolve, reject) {
        resolve(42);
    }
};

let p1 = Promise.resolve(thenable);
p1.then(function(value) {
    console.log(value); // 42
});
```



## 串联的Promise

每次调用 then() 方法或 catch() 方法实际上创建并返回了另一个 Promise，只有当第一个 Promise 被完成或拒绝后，第二个才会被解决

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(42);
});

p1.then(function(value) {
    console.log(value);
}).then(function() {
    console.log("Finished");
});

// 等价于
let p2 = new Promise(function(resolve, reject) {
    resolve(42);
});

p2.then(function() {
    console.log("Finished");
});

// 捕获错误
p1.then(function(value) {
    throw new Error("Boom!");
}).catch(function(err) {
    console.log(err.message); // "Boom!"
});
```

### Promise 链的返回值

如果在完成处理程序中指定一个返回值，则可以沿这条链继续传递数据

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(42);
});

p1.then(function(value) {
    console.log(value); // 42
    return value + 1;
}).then(function(value) {
    console.log(value); // 43
});
```



## 响应多个Promise

### Promise.all() 方法

该方法只接受一个含多个受监视 Promise 的可迭代对象，只有当所有 Promise 都被解决后返回的 Promise 才会被解决。但传入的 Promise 中只要有一个被拒绝，那么返回的 Promise 不等所有 Promise 完成就立即被拒绝

```js
let p1 = new Promise(function(resolve, reject) {
    resolve(42);
});

let p2 = new Promise(function(resolve, reject) {
    resolve(43);
});

let p3 = new Promise.all([p1, p2]);
p4.then(function(value) {
    console.log(Array.isArray(value)); // true
    console.log(value[0]); // 42
})
```



### Promise.race() 方法

传给该方法的 Promise 集合会进行竞争，如果先解决的是已完成的 Promise，那么返回的就是已完成的 Promise；如果先返回的是已拒绝的 Promise，则返回已拒绝的 Promise



